config/routes.rb
Hello::Application.routes.draw do
  resources :boys

end

app/models/boy.rb
class Boy < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boys_controller.rb
class BoysController < ApplicationController
  # GET /boys
  # GET /boys.json
  def index
    @boys = Boy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boys }
    end
  end

  # GET /boys/1
  # GET /boys/1.json
  def show
    @boy = Boy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @boy }
    end
  end

  # GET /boys/new
  # GET /boys/new.json
  def new
    @boy = Boy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @boy }
    end
  end

  # GET /boys/1/edit
  def edit
    @boy = Boy.find(params[:id])
  end

  # POST /boys
  # POST /boys.json
  def create
    @boy = Boy.new(params[:boy])

    respond_to do |format|
      if @boy.save
        format.html { redirect_to @boy, notice: 'Boy was successfully created.' }
        format.json { render json: @boy, status: :created, location: @boy }
      else
        format.html { render action: "new" }
        format.json { render json: @boy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boys/1
  # PUT /boys/1.json
  def update
    @boy = Boy.find(params[:id])

    respond_to do |format|
      if @boy.update_attributes(params[:boy])
        format.html { redirect_to @boy, notice: 'Boy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @boy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boys/1
  # DELETE /boys/1.json
  def destroy
    @boy = Boy.find(params[:id])
    @boy.destroy

    respond_to do |format|
      format.html { redirect_to boys_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boys_helper.rb
module BoysHelper
end

app/views/boys/_form.html.erb
<%= form_for(@boy) do |f| %>
  <% if @boy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boy.errors.count, "error") %> prohibited this boy from being saved:</h2>

      <ul>
      <% @boy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boys/edit.html.erb
<h1>Editing boy</h1>

<%= render 'form' %>

<%= link_to 'Show', @boy %> |
<%= link_to 'Back', boys_path %>

app/views/boys/index.html.erb
<h1>Listing boys</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boys.each do |boy| %>
  <tr>
    <td><%= boy.name %></td>
    <td><%= link_to 'Show', boy %></td>
    <td><%= link_to 'Edit', edit_boy_path(boy) %></td>
    <td><%= link_to 'Destroy', boy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Boy', new_boy_path %>

app/views/boys/new.html.erb
<h1>New boy</h1>

<%= render 'form' %>

<%= link_to 'Back', boys_path %>

app/views/boys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @boy.name %>
</p>


<%= link_to 'Edit', edit_boy_path(@boy) %> |
<%= link_to 'Back', boys_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hello</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>